### PR TITLE
style: Update skull.svg to improve readability #22

### PR DESCRIPTION
**Pull request by CaraAra**
Removed bottom jaw to reduce clutter and create a more intuitive outline.
Updated eye shape to be more in line with the mutant remix style.
Closes [#22](https://github.com/mutant-remix/mutant-remix/issues/22).

### CODE REVIEW

**Comment by CaraAra** [comment]
No idea why the third commit was added to the pr after I made it. Annoying...

**Comment by wait-what** [comment]
Doesn't follow conventional commits but whatever https://github.com/mutant-remix/mutant-remix/blob/master/CONTRIBUTING.md#general-notes

**Comment by wait-what** [comment]
What's odd is that the old svg was 150px for some reason? I'll look into this

**Comment by CaraAra** [comment]
Tried to follow the conventional commits specification to the word, what is there an issue with?

**Comment by wait-what** [comment]
yes your pr name follows conventional commits, but not your commits

**Review by wait-what — APPROVED** [review]

**Pull request merged**
