### PR TITLE
fix: revert skull changes

### PR DESCRIPTION
**Pull request by Rexogamer**
:skull:

### CODE REVIEW

**Comment by sneexy-boi** [comment]
no re-open this right now

**Comment by mdwalters** [comment]
no leave it closed

**Comment by Rexogamer** [comment]
sneexy is right tbh

**Review by sneexy-boi — APPROVED** [review]
yeah yeah looks good we should use this

**Comment by wait-what** [comment]
why

**Comment by wait-what** [comment]
I believe that the new emoji is better and more in-line with existing emoji packs, so it won't be reverted. It can be added back to extras under PUA in the future.

**Comment by janderedev** [comment]
Old one looks far better though.......

**Comment by wait-what** [comment]
ok but when

**Comment by tame1d** [comment]
nah old one definetly looks WAY better

**Comment by sneexy-boi** [comment]
theyrerightyouknow

**Pull request closed without merging**
